spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo2
    username: root
    password: rr228800
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
  mvc:
    pathmatch:
      matching-strategy=ant_path_matcher: ant_path_matcher
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
management:
  endpoints:
    web:
      exposure:
        include: "*"